### ISSUE TITLE
"influx is not a function"

### ISSUE THREAD

**Issue by titeishon** [macghriogair/yawpi#1]
Hi! 

First of all. thanks for this project, it's exactly what I'm looking for!. Unfortunately I ran into this issue when trying to set it up:

TypeError: influx is not a function
    at InfluxProxy.init (/home/pi/yawpi/src/influx-proxy.js:15:20)
    at Object.<anonymous> (/home/pi/yawpi/app.js:18:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
error: Forever detected script exited with code: 1
error: Script restart attempt #32
/home/pi/yawpi/src/influx-proxy.js:15
    this._client = influx({

It's installed in a Raspberry Pi 3 using the latest Raspbian Jessie with node v7.5.0. All dependencies are installed (async, nconf, sensortag, influx)

**Comment by macghriogair** [comment]
Dear contributor, my apologies for the late reply! 

Do you still experience this issue? I cannot reproduce it under Raspbian Jessie on a Pi 3 with Node v.6.10.2. But according to the error it looks very much like requiring the influx node module failed.
If still relevant, could you try with the latest version [v0.2.0](https://github.com/macghriogair/yawpi/commit/c76381017351c934a1ffbfa18f4d49fe18529345) which now relies on webpack for building?

Regards

**Comment by macghriogair** [comment]
Closing this due to inactivity.
